# Reference https://docs.platformio.org/en/stable/integration/ci/github-actions.html

name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - .vscode/**
      - README.md
      - LICENSE
      - .github/**
      - '!.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - .vscode/**
      - README.md
      - LICENSE
      - .github/**
      - '!.github/workflows/ci.yml'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Build Project (default environments)
        run: pio run

      # To be restored once we have a automated tests
      # - name: Run Unit Tests
      #   run: pio test --environment native

      - name: Create firmware folder
        run: |
          mkdir -p firmware
          cp ${{ github.workspace }}/.pio/build/leonardo/firmware.elf ${{ github.workspace }}/firmware/leonardo.elf
          cp ${{ github.workspace }}/.pio/build/leonardo/firmware.hex ${{ github.workspace }}/firmware/leonardo.hex
          cp ${{ github.workspace }}/.pio/build/uno_r4_wifi/firmware.elf ${{ github.workspace }}/firmware/uno_r4_wifi.elf
          cp ${{ github.workspace }}/.pio/build/uno_r4_wifi/firmware.bin ${{ github.workspace }}/firmware/uno_r4_wifi.bin
          cp ${{ github.workspace }}/.pio/build/uno_wifi_rev2/firmware.elf ${{ github.workspace }}/firmware/uno_wifi_rev2.elf
          cp ${{ github.workspace }}/.pio/build/uno_wifi_rev2/firmware.hex ${{ github.workspace }}/firmware/uno_wifi_rev2.hex

      - name: Upload Artifact (firmware)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/firmware/*
          name: firmware
          retention-days: 1
